### Ask a simple question
GET localhost:8080/chat/ask?question=What is the meaning of life

### Ask with vector store search (RAG)
GET localhost:8080/chat/ask-vector-store?question=What fruit i hate

### Ask question about image

GET localhost:8080/chat/ask-image?imageUrl=https://www.jopenspace.cz/public/images/gallery/2022/main.jpg&question=How many people are there in the photo

### Generate image of a cat

GET localhost:8080/image/cat

### Get movie details based on query (Structured output)

GET localhost:8080/chat/movie?question=What is the best ranked movie ever?

### Get list of movies based on query (Structured output)

GET localhost:8080/chat/movies?question=Give me three best movies according to metacritic with score, year, director, short description and genre

### Get list of movies currently in cinemas

GET localhost:8080/chat/movies-in-cinemas

### Get list of movies currently in cinemas with filter

GET localhost:8080/chat/movies-in-cinemas?question=Give me movies currently in cinemas with rating 80 or higher